variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - deploy  # Deployment (CD) stage

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

deploy_docker:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    # Build the Docker image without pushing it to any registry
    - docker build -t ticketwave:latest .
