variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - deploy  # Deployment (CD) stage

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

deploy_docker:
  stage: deploy  # This is now part of the CD pipeline
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "CI_REGISTRY_IMAGE is: $CI_REGISTRY_IMAGE"
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest