variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - deploy  # Deployment (CD) stage

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

deploy_docker:
  stage: deploy  # Part of the CD pipeline
  image: docker:latest
  services:
    - docker:dind
  before_script:
    # Authenticate Docker with GitLab Container Registry
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    # Build the Docker image
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    # Push the Docker image to the GitLab Container Registry
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master  # Only run on the master branch
