variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - deploy  # Deployment (CD) stage

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test

deploy_docker:
  stage: deploy  # This is now part of the CD pipeline
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker buildx create --use  # Ensure buildx is set up
    - docker buildx build --tag $CI_REGISTRY_IMAGE:latest --load .
    - docker push $CI_REGISTRY_IMAGE:latest